name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: testthedocs/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ github.actor }}:${{ github.token }}
          BUILD_DIR: docs/.vuepress/dist
          BUILD_SCRIPT: npm install && npm run docs:build
